server {
    listen 8000;
    server_name localhost;

    location ~ ^/back/storage/(.*)$ {
        alias /app/public/storage/$1;
    }

    location ~ ^/back/(.*)$ {
        fastcgi_pass pfg1-back:9000;
        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param REQUEST_URI /$1$is_args$args;
        fastcgi_param PATH_INFO /$1;
    }
}
