services:
  # Backend Laravel
  pfg1-back:
    container_name: pfg1-back
    build:
      context: .
      dockerfile: ./back/laravel-api/dev.Dockerfile
    volumes:
      - ./back/laravel-api:/app
    depends_on:
      - pfg1-postgres
    command: sh -c "cp /app/.env.example /app/.env && php artisan key:generate && php artisan migrate:fresh --seed && php-fpm"
    networks:
      - general

  # Nginx (for API)
  pfg1-nginx:
    container_name: pfg1-nginx
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./back/laravel-api/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./back/laravel-api:/app
    depends_on:
      pfg1-back:
        condition: service_started
    networks:
      - general

  pfg1-postgres:
    image: postgres:16
    container_name: pfg1-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: prf-renfe
    networks:
      - general

networks:
  general:
    driver: bridge
    name: general
