services:
  # DB
  pfg1-postgres:
    image: postgres:16
    container_name: pfg1-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: prf-renfe
    ports:
      - "5432:5432"
    networks:
      - general
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  # Backend Laravel
  pfg1-back:
    container_name: pfg1-back
    build:
      context: .
      dockerfile: ./back/laravel-api/dev.Dockerfile
    volumes:
      - ./back/laravel-api:/app
    depends_on:
      pfg1-postgres:
        condition: service_healthy
    networks:
      - general
    command: php-fpm

    # Backend Principal nodejs
  pfg1-back-node:
    container_name: pfg1-back-node
    build:
      dockerfile: ./back/principal-node/dev.Dockerfile
      context: .
    command: sh -c "cp .env.DEV .env && npm install && nodemon -L index.js"
    volumes:
      - ./back/principal-node:/usr/src/app
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    depends_on:
      - pfg1-back
    networks:
      - general

  # Nginx per mostrar el Laravel
  pfg1-nginx:
    container_name: pfg1-nginx
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./back/laravel-api/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./back/laravel-api:/app
    depends_on:
      - pfg1-back
    networks:
      - general

networks:
  general:
    driver: bridge
