# Configuració temporal per a obtenir els certificats Let's Encrypt
# S'ulitza només per a la fase d'obtenció de certificats. Un cop obtinguts, es pot restaurar nginx.conf a la versió original (que redirigeix tot a HTTPS).
server {
    listen 80;
    server_name renfe.daw.inspedralbes.cat;

    # Permitir l'accés a la ruta per a la verificació de Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirecció a HTTPS per a qualsevol altra ruta. (Inicialment, només s'utilitzarà per a la verificació, així que no afectarà el procés de certificació)
    location / {
        return 301 https://$host$request_uri;
    }
}
