server {
    listen 80;
    server_name renfe.daw.inspedralbes.cat;
    # Redirecció a HTTPS
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    http2 on;
    server_name renfe.daw.inspedralbes.cat;

    # Certificats
    ssl_certificate /etc/letsencrypt/live/renfe.daw.inspedralbes.cat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/renfe.daw.inspedralbes.cat/privkey.pem;
    
    # Configuració SSL estàndard
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # --- 1. CONFIGURACIÓ DEL FRONTEND (La Web) ---
    location / {
        root /usr/share/nginx/html;
        index index.html;

        # Això és vital si fas servir React, Vue o Angular perquè funcionin les rutes
        try_files $uri $uri/ /index.html;
    }

    # --- 2. CONFIGURACIÓ DEL BACKEND (/api) ---
    location /back/ {        
        proxy_pass http://pfg1-back:8000/;        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- 3. CONFIGURACIÓ DEL BACKEND SENSOR (/sensor) ---
    location /sensor/ {        
        proxy_pass http://pfg1-sensor:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


}